######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 25 11:00:24 2009
######################################################################

TEMPLATE = app
TARGET = banditmanchot
DEPENDPATH += .
INCLUDEPATH += .

MOC_DIR = moc
OBJECTS_DIR = obj

# Input
HEADERS += banditmanchot.h banditmanchot_interface.h \
    bmmanager.h
SOURCES += banditmanchot.cpp main.cpp \
    bmmanager.cpp

QT += widgets
